channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
    - torch==1.6.0
    - torchvision==0.7.0
    - pytorch-lightning==1.0.4
    - tqdm
    - azureml-core
    - azureml-dataprep
    - azureml-mlflow
